### ISSUE TITLE
HTML - 30 bytes

### ISSUE THREAD

**Issue by caioluders** [binarygolf/BGGP#13]
```
---BEGIN BGGP5---
Submit Date: 21/06/24
BGGP Challenge Number: 5
Author: caioluders
Online Presence (Website/Social Media):  @caioluders
Target File Type: HTML
File Size: 30 bytes
SHA256 Hash: 2b6f1c82fdaa686f70d5f0406aa2a655b7ef0b5359ad5c9efac1f48ac4913046
Target Environment (How do we run the file?): Open in any browser, should work
Any additional info?: It downloads the 5 file, not sure if this fits the rules
File contents (base64 encoded please): PGlmcmFtZSBzcmM9Ly9iaW5hcnkuZ29sZi81LzU+
---END BGGP5---
```

**Comment by netspooky** [comment]
Hi! I like this one, but it doesn't necessarily display the file. On Firefox it downloads the file, and on Chrome it opens the download dialog. If there are any required browser settings you could recommend (or other page elements you could add) that would let it fully render the iframe, then that would be acceptable!

**Comment by caioluders** [comment]
Yeah, I thought maybe only downloading was enough, will try harder to proper display it (: Thanks
