### ISSUE TITLE
Python - 20 bytes - payload in filename

### ISSUE THREAD

**Issue by caioluders** [binarygolf/BGGP#45]
```
---BEGIN BGGP5---
Submit Date: 24/06
BGGP Challenge Number: 5
Author: caioluders
Online Presence (Website/Social Media): @caioluders
Target File Type: Python
File Size: 20 bytes
SHA256 Hash: a20210490883ee1628596aec72da19d2454bd994878fa28182959f212ac1fe4a
Target Environment (How do we run the file?): Name the file as __import__('os').system('curl -L binary.golf\x2f5\x2f5')#.py , maybe needs \ before spaces and quotes
File contents (base64 encoded please): ZXhlYyhfX2ZpbGVfX1stNjA6XSk=
---END BGGPx---
```

I think that the category `Runs With CLI Arguments` is a nice way of separating and maintaining the integrity of the file's size counter. However, as we are seeing, there are other ways of externalizing the payload's content. I think that the alternate category should be `External payload` or something of the like, to note that the proper payload that solves the challenge comes from an external environment outside the script file itself. Or just ban this and anything external (CLI args included).
Thanks, sorry for the long text (:

**Comment by BusesCanFly** [comment]
```
---BEGIN VERIFICATION---
Reviewer: BusesCanFly
Review Date: 5/24/24
SHA256:  a20210490883ee1628596aec72da19d2454bd994878fa28182959f212ac1fe4a
Score: 4096 - 20 = 4,076
Note: Verified with Python 3.12.4
---END VERIFICATION---
```

Awesome stuff! Love that is messed with `sha256sum` hahaha :)
```
❯ sha256sum __import__\(\'os\'\).system\(\'curl\ -L\ binary.golf\\x2f5\\x2f5\'\)\#.py
\a20210490883ee1628596aec72da19d2454bd994878fa28182959f212ac1fe4a  __import__('os').system('curl -L binary.golf\\x2f5\\x2f5')#.py
```

**Comment by caioluders** [comment]
Hey, sorry to bother @BusesCanFly @netspooky,  I dont t think this was added to the final result. Also #125 has a 0x0a in the end for -1

**Comment by netspooky** [comment]
Ah thanks for the catch! Will revise shortly
